# **BA820 Airbnb California Market Segmentation & Housing Information Analysis**

B1 - Team 9

Team member: Lifu Li, Wenxin Liang, Yu Xu, Dizhao Zhang, Huawan Zhong

## **EDA**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
file_path="/content/drive/MyDrive/BA820_group/data/data_cleaned.csv"
data_cleaned=pd.read_csv(file_path)

In [3]:
file_path="/content/drive/MyDrive/BA820_group/data/data_roomclass_k_with_id.csv"
data_roomclass_k=pd.read_csv(file_path)

In [4]:
data_cleaned.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,property_category,property_type_numeric,room_type_numeric,percentage,percentage_room_type
0,6,https://www.airbnb.com/rooms/6,20240921043845,2024-09-21,city scrape,North Park Craftsmen House * Great for Families,This Beautiful Craftsmen house has all the mod...,"We have the best Neighborhood in San Diego, in...",https://a0.muscache.com/pictures/miso/Hosting-...,29,...,1,1,0,0,0.82,Standalone Homes,0,0,57.625594,73.101686
1,109,https://www.airbnb.com/rooms/109,20240904164210,2024-09-05,city scrape,Amazing bright elegant condo park front *UPGRA...,"*** Unit upgraded with new bamboo flooring, ne...",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,521,...,1,1,0,0,0.01,Apartments & Condos,1,0,7.187528,73.101686
2,958,https://www.airbnb.com/rooms/958,20240904163718,2024-09-04,city scrape,"Bright, Modern Garden Unit - 1BR/1BTH",Our bright garden unit overlooks a lovely back...,Quiet cul de sac in friendly neighborhood<br /...,https://a0.muscache.com/pictures/b7c2a199-4c17...,1169,...,1,1,0,0,2.46,Apartments & Condos,1,0,7.187528,73.101686
3,2708,https://www.airbnb.com/rooms/2708,20240904164210,2024-09-05,city scrape,Runyon Canyon | Beau Furn Mirror Mini-Suite Fi...,"Run Runyon Canyon, Our Gym & Sauna Open <br />...","Walk and run to Runyon Canyon, it is open!<br ...",https://a0.muscache.com/pictures/miso/Hosting-...,3008,...,2,0,2,0,0.34,Private Rooms,4,1,20.360483,25.073012
4,2732,https://www.airbnb.com/rooms/2732,20240904164210,2024-09-05,city scrape,Zen Life at the Beach,An oasis of tranquility awaits you.,"This is the best part of Santa Monica. Quiet, ...",https://a0.muscache.com/pictures/1082974/0f74c...,3041,...,2,1,1,0,0.15,Private Rooms,4,1,20.360483,25.073012

In [5]:
data_roomclass_k.head()

,host_response_rate,host_acceptance_rate,host_listings_count,property_type_numeric,room_type_numeric,accommodates,bathrooms,bedrooms,beds,price,...,number_of_reviews_ltm,number_of_reviews_l30d,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,cluster_label,id
0,100.000000,92.000000,1.0,0.0,0.0,8,2.0,3.0,6.0,249.0,...,9,0,4.83,4.70,4.99,4.97,4.79,4.80,1,6
1,95.873592,87.789348,1.0,1.0,0.0,6,2.0,2.0,2.0,129.0,...,0,0,5.00,5.00,3.00,4.00,5.00,4.00,2,109
2,100.000000,100.000000,1.0,1.0,0.0,3,1.0,1.0,2.0,186.0,...,46,2,4.93,4.93,4.96,4.89,4.97,4.76,1,958
3,100.000000,100.000000,2.0,3.0,1.0,1,1.0,1.0,1.0,86.0,...,3,0,4.81,4.93,5.00,4.98,4.95,4.86,0,2708
4,100.000000,78.000000,2.0,3.0,1.0,1,1.0,1.0,1.0,139.0,...,0,0,4.26,4.58,4.39,4.48,4.91,4.22,1,2732

In [6]:
merged_data = data_cleaned.merge(data_roomclass_k, left_index=True, right_index=True,  how="left")
merged_data.head()
merged_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45583 entries, 0 to 45582
Columns: 107 entries, id_x to id_y
dtypes: float64(42), int64(31), object(34)
memory usage: 37.2+ MB

In [7]:
merged_data["cluster_label"].isnull().sum()
merged_data.dropna(subset=['cluster_label'])

,id_x,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,number_of_reviews_ltm_y,number_of_reviews_l30d_y,review_scores_accuracy_y,review_scores_cleanliness_y,review_scores_checkin_y,review_scores_communication_y,review_scores_location_y,review_scores_value_y,cluster_label,id_y
0,6,https://www.airbnb.com/rooms/6,20240921043845,2024-09-21,city scrape,North Park Craftsmen House * Great for Families,This Beautiful Craftsmen house has all the mod...,"We have the best Neighborhood in San Diego, in...",https://a0.muscache.com/pictures/miso/Hosting-...,29,...,9,0,4.83,4.70,4.99,4.97,4.79,4.80,1,6
1,109,https://www.airbnb.com/rooms/109,20240904164210,2024-09-05,city scrape,Amazing bright elegant condo park front *UPGRA...,"*** Unit upgraded with new bamboo flooring, ne...",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,521,...,0,0,5.00,5.00,3.00,4.00,5.00,4.00,2,109
2,958,https://www.airbnb.com/rooms/958,20240904163718,2024-09-04,city scrape,"Bright, Modern Garden Unit - 1BR/1BTH",Our bright garden unit overlooks a lovely back...,Quiet cul de sac in friendly neighborhood<br /...,https://a0.muscache.com/pictures/b7c2a199-4c17...,1169,...,46,2,4.93,4.93,4.96,4.89,4.97,4.76,1,958
3,2708,https://www.airbnb.com/rooms/2708,20240904164210,2024-09-05,city scrape,Runyon Canyon | Beau Furn Mirror Mini-Suite Fi...,"Run Runyon Canyon, Our Gym & Sauna Open <br />...","Walk and run to Runyon Canyon, it is open!<br ...",https://a0.muscache.com/pictures/miso/Hosting-...,3008,...,3,0,4.81,4.93,5.00,4.98,4.95,4.86,0,2708
4,2732,https://www.airbnb.com/rooms/2732,20240904164210,2024-09-05,city scrape,Zen Life at the Beach,An oasis of tranquility awaits you.,"This is the best part of Santa Monica. Quiet, ...",https://a0.muscache.com/pictures/1082974/0f74c...,3041,...,0,0,4.26,4.58,4.39,4.48,4.91,4.22,1,2732
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45578,1244362166123044607,https://www.airbnb.com/rooms/1244362166123044607,20240921192422,2024-09-21,city scrape,"Cozy Room near SJ Airport, Levi Stadium",l Full Size bed<br />Room in N. San Jose near ...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,415830949,...,1,1,5.00,5.00,4.00,5.00,5.00,5.00,0,1244362166123044607
45579,1244898988351466083,https://www.airbnb.com/rooms/1244898988351466083,20240921043845,2024-09-21,city scrape,Modern Lux STU in Historic Hostel,A Newly Renovated Studio in a luxury historic ...,NaN,https://a0.muscache.com/pictures/prohost-api/H...,301775154,...,1,1,5.00,5.00,5.00,5.00,5.00,5.00,1,1244898988351466083
45580,1244936374575241213,https://www.airbnb.com/rooms/1244936374575241213,20240921043830,2024-09-21,city scrape,Spacious 2 bdrm downtown Oakland,Light filled spacious 2 bed 2 bath apartment i...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,9734766,...,1,1,5.00,5.00,5.00,5.00,5.00,5.00,0,1244936374575241213
45581,1245671026749361856,https://www.airbnb.com/rooms/1245671026749361856,20240921043830,2024-09-21,city scrape,3BDR luxe home in the hills with Bay Area views,Welcome to your home away from home! This stun...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,55187955,...,1,1,5.00,5.00,5.00,5.00,5.00,5.00,1,1245671026749361856
45582,1249262278820434112,https://www.airbnb.com/rooms/1249262278820434112,20240921043845,2024-09-21,city scrape,"Diamond Gem-private yard, hot tub, close to beach","Tucked away on a quiet, residential street in ...",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,486034681,...,8,1,4.63,4.63,4.88,4.50,4.63,4.38,0,1249262278820434112

In [8]:
merged_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45583 entries, 0 to 45582
Columns: 107 entries, id_x to id_y
dtypes: float64(42), int64(31), object(34)
memory usage: 37.2+ MB

## **Data Cleaning**

In [9]:
merged_data_amentities = merged_data[["amenities","cluster_label"]]
merged_data_amentities.isnull().sum()
merged_data_amentities.dropna(subset=['cluster_label'], inplace = True)
merged_data_amentities.info()
merged_data_amentities.duplicated().sum()
merged_data_amentities.drop_duplicates(inplace = True)
merged_data_amentities.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45583 entries, 0 to 45582
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   amenities      45583 non-null  object
 1   cluster_label  45583 non-null  int64
dtypes: int64(1), object(1)
memory usage: 712.4+ KB

<ipython-input-9-16510a57b297>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data_amentities.dropna(subset=['cluster_label'], inplace = True)

<class 'pandas.core.frame.DataFrame'>
Index: 43863 entries, 0 to 45582
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   amenities      43863 non-null  object
 1   cluster_label  43863 non-null  int64
dtypes: int64(1), object(1)
memory usage: 1.0+ MB

<ipython-input-9-16510a57b297>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data_amentities.drop_duplicates(inplace = True)

In [10]:
import ast

# Convert string representation of lists into actual lists
merged_data_amentities["amenities"] = merged_data_amentities["amenities"].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)

# Remove items containing "%\\%" from each list
merged_data_amentities["amenities"] = merged_data_amentities["amenities"].apply(lambda x: [item for item in x if "%\\%" not in str(item)] if isinstance(x, list) else x)

<ipython-input-10-47a960b8a8a1>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data_amentities["amenities"] = merged_data_amentities["amenities"].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)
<ipython-input-10-47a960b8a8a1>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data_amentities["amenities"] = merged_data_amentities["amenities"].apply(lambda x: [item for item in x if "%\\%" not in str(item)] if isinstance(x, list) else x)

In [11]:
# divide the group into 3 clusters
cluster_1 = merged_data_amentities[merged_data_amentities['cluster_label'] == 0.0]
cluster_2 = merged_data_amentities[merged_data_amentities['cluster_label'] == 1.0]
cluster_3 = merged_data_amentities[merged_data_amentities['cluster_label'] == 2.0]

## **Association Rules**

In [12]:
cluster_1_test = cluster_1["amenities"].tolist()
cluster_2_test = cluster_2["amenities"].tolist()
cluster_3_test = cluster_3["amenities"].tolist()

In [13]:
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
from mlxtend.preprocessing import TransactionEncoder
from collections import Counter

def flatten_list(lst, min_n, max_n):
    flat_list = []
    for sublist in lst:
        if isinstance(sublist, list):
            flat_list += sublist
        else:
            flat_list.append(sublist)

    counter = Counter(flat_list)

    max_n = min(max_n, len(counter))
    min_n = min(min_n, max_n)

    top_values = [item[0] for item in counter.most_common(max_n)[min_n-1:max_n]]

    filtered_data = [[item for item in amenities if item in top_values] for amenities in lst]

    te = TransactionEncoder()
    transactions = te.fit_transform(filtered_data)

    df_encoded = pd.DataFrame(transactions, columns=te.columns_)
    return df_encoded

In [14]:
flatten_list_1 = flatten_list(cluster_1_test, 12, 27)
flatten_list_1

,Bed linens,Cleaning products,Dedicated workspace,Dining table,Dishwasher,Extra pillows and blankets,Fire extinguisher,First aid kit,Free parking on premises,Freezer,Iron,Long term stays allowed,Refrigerator,Self check-in,Shampoo,TV
0,True,True,True,False,True,True,True,True,True,True,True,True,False,False,False,False
1,True,True,True,True,True,True,True,True,True,True,True,True,True,False,True,False
2,False,False,True,False,False,False,True,False,True,False,True,False,True,True,False,False
3,True,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False
4,True,True,True,False,True,True,False,False,True,False,True,True,True,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15236,True,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False
15237,True,True,True,False,True,False,False,False,False,True,True,True,True,False,True,True
15238,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True
15239,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True
15240,True,False,True,True,True,False,True,False,True,False,True,False,True,True,True,True

In [15]:
frequent_itemsets_1 = apriori(flatten_list_1, min_support=0.5, use_colnames=True)
frequent_itemsets_1.sort_values(by="support", ascending=False)

     support                                  itemsets
12  0.744308                            (Refrigerator)
0   0.740896                              (Bed linens)
10  0.724296                                    (Iron)
2   0.706647                     (Dedicated workspace)
14  0.688472                                 (Shampoo)
6   0.676071                       (Fire extinguisher)
13  0.665573                           (Self check-in)
22  0.618267                (Refrigerator, Bed linens)
15  0.612689                                      (TV)
20  0.609474                        (Iron, Bed linens)
8   0.594646                (Free parking on premises)
30  0.593990                      (Refrigerator, Iron)
11  0.588413                 (Long term stays allowed)
34  0.584148                   (Refrigerator, Shampoo)
24  0.577127                     (Bed linens, Shampoo)
3   0.575881                            (Dining table)
7   0.568729                           (First aid kit)
32  0.567089                           (Iron, Shampoo)
4   0.551079                              (Dishwasher)
1   0.549242                       (Cleaning products)
16  0.547996         (Bed linens, Dedicated workspace)
9   0.545502                                 (Freezer)
5   0.543862              (Extra pillows and blankets)
27  0.540844       (Refrigerator, Dedicated workspace)
26  0.540647               (Iron, Dedicated workspace)
33  0.532577             (Refrigerator, Self check-in)
21  0.530215     (Bed linens, Long term stays allowed)
23  0.529296               (Bed linens, Self check-in)
31  0.527656                     (Iron, Self check-in)
19  0.527524           (Fire extinguisher, Bed linens)
28  0.522735                 (Iron, Fire extinguisher)
17  0.518470                (Dining table, Bed linens)
29  0.518273         (Refrigerator, Fire extinguisher)
35  0.517617          (Refrigerator, Iron, Bed linens)
18  0.507513  (Extra pillows and blankets, Bed linens)
36  0.507447       (Refrigerator, Bed linens, Shampoo)
25  0.502854  (Fire extinguisher, Dedicated workspace)

In [16]:
rules_1 = association_rules(frequent_itemsets_1, metric = "support", min_threshold=0.05)
rules_1

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Bed linens),(Dedicated workspace),0.740896,0.706647,0.547996,0.739639,1.046688,1.0,0.024444,1.126717,0.172154,0.609190,0.112465,0.757563
1,(Dedicated workspace),(Bed linens),0.706647,0.740896,0.547996,0.775487,1.046688,1.0,0.024444,1.154072,0.152055,0.609190,0.133503,0.757563
2,(Dining table),(Bed linens),0.575881,0.740896,0.518470,0.900308,1.215160,1.0,0.091802,2.599033,0.417485,0.649462,0.615241,0.800048
3,(Bed linens),(Dining table),0.740896,0.575881,0.518470,0.699787,1.215160,1.0,0.091802,1.412730,0.683368,0.649462,0.292150,0.800048
4,(Extra pillows and blankets),(Bed linens),0.543862,0.740896,0.507513,0.933164,1.259508,1.0,0.104567,3.876734,0.451703,0.652963,0.742051,0.809081
5,(Bed linens),(Extra pillows and blankets),0.740896,0.543862,0.507513,0.684998,1.259508,1.0,0.104567,1.448049,0.795198,0.652963,0.309416,0.809081
6,(Fire extinguisher),(Bed linens),0.676071,0.740896,0.527524,0.780280,1.053156,1.0,0.026626,1.179242,0.155816,0.593095,0.151998,0.746144
7,(Bed linens),(Fire extinguisher),0.740896,0.676071,0.527524,0.712009,1.053156,1.0,0.026626,1.124786,0.194799,0.593095,0.110942,0.746144
8,(Iron),(Bed linens),0.724296,0.740896,0.609474,0.841471,1.135748,1.0,0.072846,1.634426,0.433519,0.712237,0.388165,0.832044
9,(Bed linens),(Iron),0.740896,0.724296,0.609474,0.822618,1.135748,1.0,0.072846,1.554292,0.461293,0.712237,0.356620,0.832044
10,(Bed linens),(Long term stays allowed),0.740896,0.588413,0.530215,0.715639,1.216220,1.0,0.094262,1.447413,0.686135,0.663519,0.309112,0.808366
11,(Long term stays allowed),(Bed linens),0.588413,0.740896,0.530215,0.901093,1.216220,1.0,0.094262,2.619664,0.431938,0.663519,0.618272,0.808366
12,(Refrigerator),(Bed linens),0.744308,0.740896,0.618267,0.830659,1.121155,1.0,0.066811,1.530074,0.422628,0.713161,0.346437,0.832572
13,(Bed linens),(Refrigerator),0.740896,0.744308,0.618267,0.834485,1.121155,1.0,0.066811,1.544822,0.417063,0.713161,0.352676,0.832572
14,(Bed linens),(Self check-in),0.740896,0.665573,0.529296,0.714400,1.073360,1.0,0.036175,1.170961,0.263779,0.603411,0.146000,0.754824
15,(Self check-in),(Bed linens),0.665573,0.740896,0.529296,0.795248,1.073360,1.0,0.036175,1.265454,0.204368,0.603411,0.209770,0.754824
16,(Bed linens),(Shampoo),0.740896,0.688472,0.577127,0.778959,1.131431,1.0,0.067041,1.409365,0.448329,0.677188,0.290461,0.808616
17,(Shampoo),(Bed linens),0.688472,0.740896,0.577127,0.838273,1.131431,1.0,0.067041,1.602107,0.372883,0.677188,0.375822,0.808616
18,(Fire extinguisher),(Dedicated workspace),0.676071,0.706647,0.502854,0.743789,1.052561,1.0,0.025111,1.144967,0.154159,0.571514,0.126613,0.727698
19,(Dedicated workspace),(Fire extinguisher),0.706647,0.676071,0.502854,0.711606,1.052561,1.0,0.025111,1.123218,0.170227,0.571514,0.109701,0.727698
20,(Iron),(Dedicated workspace),0.724296,0.706647,0.540647,0.746444,1.056319,1.0,0.028825,1.156959,0.193384,0.607267,0.135665,0.755766
21,(Dedicated workspace),(Iron),0.706647,0.724296,0.540647,0.765088,1.056319,1.0,0.028825,1.173648,0.181749,0.607267,0.147956,0.755766
22,(Refrigerator),(Dedicated workspace),0.744308,0.706647,0.540844,0.726640,1.028293,1.0,0.014881,1.073138,0.107608,0.594261,0.068154,0.746003
23,(Dedicated workspace),(Refrigerator),0.706647,0.744308,0.540844,0.765367,1.028293,1.0,0.014881,1.089751,0.093793,0.594261,0.082359,0.746003
24,(Iron),(Fire extinguisher),0.724296,0.676071,0.522735,0.721714,1.067512,1.0,0.033059,1.164014,0.229385,0.595619,0.140904,0.747454
25,(Fire extinguisher),(Iron),0.676071,0.724296,0.522735,0.773195,1.067512,1.0,0.033059,1.215597,0.195235,0.595619,0.177359,0.747454
26,(Refrigerator),(Fire extinguisher),0.744308,0.676071,0.518273,0.696315,1.029944,1.0,0.015068,1.066662,0.113704,0.574515,0.062496,0.731455
27,(Fire extinguisher),(Refrigerator),0.676071,0.744308,0.518273,0.766595,1.029944,1.0,0.015068,1.095488,0.089752,0.574515,0.087165,0.731455
28,(Refrigerator),(Iron),0.744308,0.724296,0.593990,0.798043,1.101818,1.0,0.054890,1.365160,0.361409,0.679145,0.267485,0.809068
29,(Iron),(Refrigerator),0.724296,0.744308,0.593990,0.820092,1.101818,1.0,0.054890,1.421240,0.335177,0.679145,0.296389,0.809068
30,(Iron),(Self check-in),0.724296,0.665573,0.527656,0.728508,1.094557,1.0,0.045584,1.231811,0.313339,0.611978,0.188187,0.760646
31,(Self check-in),(Iron),0.665573,0.724296,0.527656,0.792784,1.094557,1.0,0.045584,1.330513,0.258319,0.611978,0.248410,0.760646
32,(Iron),(Shampoo),0.724296,0.688472,0.567089,0.782951,1.137231,1.0,0.068431,1.435292,0.437683,0.670572,0.303278,0.803322
33,(Shampoo),(Iron),0.688472,0.724296,0.567089,0.823692,1.137231,1.0,0.068431,1.563762,0.387352,0.670572,0.360516,0.803322
34,(Refrigerator),(Self check-in),0.744308,0.665573,0.532577,0.715532,1.075062,1.0,0.037185,1.175624,0.273068,0.607060,0.149388,0.757855
35,(Self check-in),(Refrigerator),0.665573,0.744308,0.532577,0.800177,1.075062,1.0,0.037185,1.279595,0.208779,0.607060,0.218503,0.757855
36,(Refrigerator),(Shampoo),0.744308,0.688472,0.584148,0.784820,1.139945,1.0,0.071713,1.447757,0.480128,0.688341,0.309276,0.816645
37,(Shampoo),(Refrigerator),0.688472,0.744308,0.584148,0.848470,1.139945,1.0,0.071713,1.687406,0.394073,0.688341,0.407374,0.816645
38,"(Refrigerator, Iron)",(Bed linens),0.593990,0.740896,0.517617,0.871424,1.176175,1.0,0.077532,2.015177,0.368923,0.633349,0.503766,0.785030
39,"(Refrigerator, Bed linens)",(Iron),0.618267,0.724296,0.517617,0.837207,1.155890,1.0,0.069809,1.693583,0.353298,0.627456,0.409536,0.775927
40,"(Iron, Bed linens)",(Refrigerator),0.609474,0.744308,0.517617,0.849284,1.141038,1.0,0.063980,1.696516,0.316510,0.619036,0.410557,0.772359
41,(Refrigerator),"(Iron, Bed linens)",0.744308,0.609474,0.517617,0.695434,1.141038,1.0,0.063980,1.282235,0.483415,0.619036,0.220112,0.772359
42,(Iron),"(Refrigerator, Bed linens)",0.724296,0.618267,0.517617,0.714648,1.155890,1.0,0.069809,1.337764,0.489169,0.627456,0.252484,0.775927
43,(Bed linens),"(Refrigerator, Iron)",0.740896,0.593990,0.517617,0.698636,1.176175,1.0,0.077532,1.347242,0.578095,0.633349,0.257743,0.785030
44,"(Refrigerator, Bed linens)",(Shampoo),0.618267,0.688472,0.507447,0.820758,1.192144,1.0,0.081788,1.738028,0.422219,0.634871,0.424635,0.778910
45,"(Refrigerator, Shampoo)",(Bed linens),0.584148,0.740896,0.507447,0.868696,1.172493,1.0,0.074654,1.973311,0.353772,0.620656,0.493238,0.776803
46,"(Bed linens, Shampoo)",(Refrigerator),0.577127,0.744308,0.507447,0.879263,1.181316,1.0,0.077886,2.117764,0.362962,0.623408,0.527804,0.780517
47,(Refrigerator),"(Bed linens, Shampoo)",0.744308,0.577127,0.507447,0.681770,1.181316,1.0,0.077886,1.328827,0.600280,0.623408,0.247457,0.780517
48,(Bed linens),"(Refrigerator, Shampoo)",0.740896,0.584148,0.507447,0.684910,1.172493,1.0,0.074654,1.319787,0.567791,0.620656,0.242302,0.776803
49,(Shampoo),"(Refrigerator, Bed linens)",0.688472,0.618267,0.507447,0.737063,1.192144,1.0,0.081788,1.451805,0.517370,0.634871,0.311202,0.778910

In [17]:
flatten_list_2 = flatten_list(cluster_2_test, 12, 27)
flatten_list_2

,Bed linens,Cleaning products,Cooking basics,Dedicated workspace,Dining table,Dishwasher,Extra pillows and blankets,Fire extinguisher,First aid kit,Free street parking,Heating,Private entrance,Refrigerator,Self check-in,Shampoo,Toaster
0,True,True,True,True,True,True,True,True,True,True,True,True,False,True,True,False
1,False,True,True,False,True,False,True,False,True,False,True,True,True,True,False,True
2,False,False,True,True,False,False,False,False,False,True,True,False,True,False,True,False
3,False,False,True,True,False,False,False,True,True,True,True,False,True,True,True,False
4,True,True,True,True,True,True,True,True,True,True,False,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17036,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False
17037,True,False,True,False,False,True,True,False,False,False,True,False,True,False,True,False
17038,True,True,True,True,True,True,True,True,True,True,False,False,True,True,False,True
17039,True,False,False,False,False,False,False,True,False,False,True,False,True,False,True,False
17040,True,False,True,True,True,True,False,False,True,False,True,False,True,True,False,True

In [18]:
frequent_itemsets_2 = apriori(flatten_list_2, min_support=0.5, use_colnames=True)
frequent_itemsets_2.sort_values(by="support", ascending=False)

     support                                           itemsets
0   0.786221                                       (Bed linens)
2   0.782348                                   (Cooking basics)
12  0.765272                                     (Refrigerator)
14  0.755061                                          (Shampoo)
7   0.740567                                (Fire extinguisher)
..       ...                                                ...
40  0.502435         (Refrigerator, Extra pillows and blankets)
27  0.500792                     (Dining table, Cooking basics)
55  0.500675  (Free street parking, Bed linens, Cooking basics)
18  0.500440                         (Dining table, Bed linens)
46  0.500323                           (Shampoo, First aid kit)

[63 rows x 2 columns]

In [19]:
rules_2 = association_rules(frequent_itemsets_2, metric = "support", min_threshold=0.05)
rules_2

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Bed linens),(Cooking basics),0.786221,0.782348,0.671616,0.854232,1.091882,1.0,0.056516,1.493136,0.393631,0.748773,0.330269,0.856346
1,(Cooking basics),(Bed linens),0.782348,0.786221,0.671616,0.858461,1.091882,1.0,0.056516,1.510384,0.386627,0.748773,0.337917,0.856346
2,(Bed linens),(Dedicated workspace),0.786221,0.664104,0.549968,0.699507,1.053310,1.0,0.027835,1.117817,0.236748,0.610832,0.105399,0.763821
3,(Dedicated workspace),(Bed linens),0.664104,0.786221,0.549968,0.828135,1.053310,1.0,0.027835,1.243872,0.150676,0.610832,0.196059,0.763821
4,(Dining table),(Bed linens),0.537762,0.786221,0.500440,0.930598,1.183633,1.0,0.077640,3.080293,0.335636,0.607667,0.675356,0.783555
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129,"(Refrigerator, Cooking basics)",(Shampoo),0.665278,0.755061,0.542398,0.815295,1.079773,1.0,0.040072,1.326108,0.220719,0.617806,0.245914,0.766822
130,"(Shampoo, Cooking basics)",(Refrigerator),0.611936,0.765272,0.542398,0.886364,1.158233,1.0,0.074100,2.065606,0.352046,0.649726,0.515881,0.797564
131,(Refrigerator),"(Shampoo, Cooking basics)",0.765272,0.611936,0.542398,0.708765,1.158233,1.0,0.074100,1.332476,0.582019,0.649726,0.249517,0.797564
132,(Shampoo),"(Refrigerator, Cooking basics)",0.755061,0.665278,0.542398,0.718349,1.079773,1.0,0.040072,1.188430,0.301625,0.617806,0.158554,0.766822
133,(Cooking basics),"(Refrigerator, Shampoo)",0.782348,0.615281,0.542398,0.693294,1.126793,1.0,0.061034,1.254360,0.517000,0.634212,0.202780,0.787420

In [20]:
flatten_list_3 = flatten_list(cluster_3_test, 12, 27)
flatten_list_3

,Bed linens,Coffee maker,Cooking basics,Dedicated workspace,Dishwasher,Extra pillows and blankets,Fire extinguisher,First aid kit,Free parking on premises,Free street parking,Heating,Long term stays allowed,Private entrance,Refrigerator,Self check-in,Shampoo
0,False,True,False,True,False,False,True,True,True,False,True,False,False,True,False,True
1,False,False,True,True,False,False,False,False,False,True,True,False,False,True,False,True
2,True,True,False,False,False,True,False,False,False,True,True,False,False,False,True,True
3,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
4,True,False,True,True,True,True,True,True,False,True,True,True,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11576,True,False,True,False,False,True,True,True,True,False,False,False,False,True,True,True
11577,False,False,False,True,False,False,True,False,True,False,False,False,False,False,False,False
11578,False,False,False,True,False,False,False,True,True,False,False,True,False,True,True,False
11579,True,False,True,True,True,True,False,False,True,True,False,True,False,True,False,False
11580,True,True,True,True,True,True,True,True,True,True,True,False,False,True,True,True

In [21]:
frequent_itemsets_3 = apriori(flatten_list_3, min_support=0.5, use_colnames=True)
frequent_itemsets_3.sort_values(by="support", ascending=False)

     support                                           itemsets
2   0.796391                                   (Cooking basics)
13  0.795095                                     (Refrigerator)
15  0.776962                                          (Shampoo)
0   0.732838                                       (Bed linens)
10  0.704775                                          (Heating)
14  0.700803                                    (Self check-in)
33  0.693118                     (Refrigerator, Cooking basics)
6   0.673431                                (Fire extinguisher)
46  0.648821                            (Refrigerator, Shampoo)
16  0.645540                       (Bed linens, Cooking basics)
9   0.642259                              (Free street parking)
35  0.637596                          (Shampoo, Cooking basics)
11  0.631638                          (Long term stays allowed)
21  0.631293                         (Refrigerator, Bed linens)
3   0.621967                              (Dedicated workspace)
34  0.600725                    (Self check-in, Cooking basics)
23  0.595285                              (Bed linens, Shampoo)
45  0.586478                      (Refrigerator, Self check-in)
12  0.583801                                 (Private entrance)
41  0.580520                            (Refrigerator, Heating)
8   0.578188                         (Free parking on premises)
42  0.576634                                 (Heating, Shampoo)
1   0.576289                                     (Coffee maker)
7   0.574734                                    (First aid kit)
49  0.574648         (Refrigerator, Bed linens, Cooking basics)
54  0.573353            (Refrigerator, Shampoo, Cooking basics)
5   0.566963                       (Extra pillows and blankets)
47  0.564373                           (Self check-in, Shampoo)
28  0.560919                (Fire extinguisher, Cooking basics)
31  0.559969          (Long term stays allowed, Cooking basics)
4   0.557983                                       (Dishwasher)
22  0.556170                        (Bed linens, Self check-in)
20  0.554184              (Bed linens, Long term stays allowed)
29  0.552629              (Free street parking, Cooking basics)
30  0.550212                          (Heating, Cooking basics)
37  0.546671                  (Refrigerator, Fire extinguisher)
43  0.544340            (Refrigerator, Long term stays allowed)
17  0.541318           (Extra pillows and blankets, Bed linens)
39  0.540195                (Free street parking, Refrigerator)
38  0.536569                       (Fire extinguisher, Shampoo)
24  0.535619                       (Coffee maker, Refrigerator)
26  0.531992                       (Dishwasher, Cooking basics)
51  0.528020                (Refrigerator, Bed linens, Shampoo)
25  0.526725              (Dedicated workspace, Cooking basics)
53  0.525171      (Refrigerator, Self check-in, Cooking basics)
50  0.523789              (Bed linens, Shampoo, Cooking basics)
18  0.523703                    (Fire extinguisher, Bed linens)
19  0.521630                  (Free street parking, Bed linens)
40  0.517313                     (Free street parking, Shampoo)
44  0.510405                 (Shampoo, Long term stays allowed)
36  0.509196                (Refrigerator, Dedicated workspace)
27  0.508505       (Extra pillows and blankets, Cooking basics)
48  0.504361  (Bed linens, Long term stays allowed, Cooking ...
32  0.501511                 (Private entrance, Cooking basics)
52  0.501338            (Refrigerator, Heating, Cooking basics)

In [22]:
rules_3 = association_rules(frequent_itemsets_3, metric = "support", min_threshold=0.05)
rules_3

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Bed linens),(Cooking basics),0.732838,0.796391,0.645540,0.880877,1.106086,1.0,0.061915,1.709231,0.359001,0.730506,0.414942,0.845729
1,(Cooking basics),(Bed linens),0.796391,0.732838,0.645540,0.810582,1.106086,1.0,0.061915,1.410437,0.471055,0.730506,0.291000,0.845729
2,(Extra pillows and blankets),(Bed linens),0.566963,0.732838,0.541318,0.954767,1.302835,1.0,0.125825,5.906343,0.536774,0.713684,0.830691,0.846713
3,(Bed linens),(Extra pillows and blankets),0.732838,0.566963,0.541318,0.738659,1.302835,1.0,0.125825,1.656981,0.870045,0.713684,0.396493,0.846713
4,(Fire extinguisher),(Bed linens),0.673431,0.732838,0.523703,0.777664,1.061167,1.0,0.030187,1.201611,0.176505,0.593386,0.167784,0.746143
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,"(Refrigerator, Cooking basics)",(Shampoo),0.693118,0.776962,0.573353,0.827208,1.064670,1.0,0.034826,1.290789,0.197931,0.639384,0.225280,0.782575
102,"(Shampoo, Cooking basics)",(Refrigerator),0.637596,0.795095,0.573353,0.899242,1.130986,1.0,0.066403,2.033623,0.319576,0.667203,0.508267,0.810177
103,(Refrigerator),"(Shampoo, Cooking basics)",0.795095,0.637596,0.573353,0.721112,1.130986,1.0,0.066403,1.299461,0.565217,0.667203,0.230450,0.810177
104,(Shampoo),"(Refrigerator, Cooking basics)",0.776962,0.693118,0.573353,0.737942,1.064670,1.0,0.034826,1.171045,0.272338,0.639384,0.146062,0.782575
105,(Cooking basics),"(Refrigerator, Shampoo)",0.796391,0.648821,0.573353,0.719939,1.109611,1.0,0.056638,1.253938,0.485161,0.657621,0.202512,0.801812